# config.yml (tek item / tüm site 1 row)
media_folder: "assets"
public_folder: "/assets"

backend:
  name: git-gateway
  branch: main

logo_url: "/assets/logo.png"
locale: "tr"
editor:
  preview: false

collections:
  - name: "site"
    label: "Site Ayarları"
    files:
      - file: "content/site.json"
        label: "Tüm Site"
        name: "site"
        format: "json"
        fields:
          - label: "Slider Resimleri"
            name: "slider"
            widget: "list"
            fields:
              - { label: "Resim", name: "image", widget: "image" }
          - label: "Videolar"
            name: "videos"
            widget: "list"
            fields:
              - { label: "Video URL (YouTube)", name: "file", widget: "string", hint: "YouTube video URL'si girin (örn: https://www.youtube.com/watch?v=VIDEO_ID)" }
              - { label: "Video Başlığı", name: "title", widget: "string", required: false, hint: "Video başlığı (opsiyonel)" }
