# config.yml (tek item / tüm site 1 row)
media_folder: "assets"
public_folder: "/assets"

backend:
  name: git-gateway
  branch: main

logo_url: "/assets/logo.png"
locale: "tr"
editor:
  preview: false

collections:
  - name: "site"
    label: "Site Ayarları"
    files:
      - file: "content/site.json"
        label: "Tüm Site"
        name: "site"
        format: "json"
        fields:
          - { label: "Öne çıkan resim", name: "featured_image", widget: "image" }
          - label: "Videolar"
            name: "videos"
            widget: "list"
            fields:
              - { label: "Video", name: "file", widget: "file" }
